// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIYSRZHEabnyUkUsVcFseq8Mhbgwv-YKI',
    appId: '1:995903342869:web:b3e12351ae6f5c8aaa011c',
    messagingSenderId: '995903342869',
    projectId: 'flutter-data-firebase-e54bb',
    authDomain: 'flutter-data-firebase-e54bb.firebaseapp.com',
    databaseURL: 'https://flutter-data-firebase-e54bb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-data-firebase-e54bb.appspot.com',
    measurementId: 'G-QYYDGV7H3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy0_NiA7wWtxNN79eDPRkKHY7-QliZvGo',
    appId: '1:995903342869:android:bb2ebf6b4a3540f6aa011c',
    messagingSenderId: '995903342869',
    projectId: 'flutter-data-firebase-e54bb',
    databaseURL: 'https://flutter-data-firebase-e54bb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-data-firebase-e54bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhvIVZRBgOa_pcpGK0r75O7ceTQT21mjQ',
    appId: '1:995903342869:ios:05f6d33b991ca6f3aa011c',
    messagingSenderId: '995903342869',
    projectId: 'flutter-data-firebase-e54bb',
    databaseURL: 'https://flutter-data-firebase-e54bb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-data-firebase-e54bb.appspot.com',
    iosClientId: '995903342869-m6pdsandss9etamltrdtv49ah6esojda.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTodoList',
  );
}
